# Generated by Django 3.2.16 on 2023-04-09 12:27

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='Название книги')),
                ('author', models.CharField(max_length=300, verbose_name='Автор книги')),
                ('description', models.CharField(max_length=3000, verbose_name='Краткое описание книги')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр книги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя читателя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия читателя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email читателя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('score', models.IntegerField(default=10, verbose_name='Рейтинг Читателя')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
                'ordering': ('username',),
            },
        ),
        migrations.CreateModel(
            name='BooksRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи книги')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата книги')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books', verbose_name='Книга')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.readers', verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Книга в аренде',
                'verbose_name_plural': 'Книги в аренде',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='rented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_books', to='book.readers', verbose_name='На руках у ...'),
        ),
    ]
