# Generated by Django 3.2.16 on 2023-04-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booksrent',
            name='reader',
            field=models.ForeignKey(help_text='Укажите Читателя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
        migrations.AddField(
            model_name='books',
            name='rented_by',
            field=models.ForeignKey(blank=True, help_text='Укажите пользователя, у которого книга находиться на руках', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_books', to=settings.AUTH_USER_MODEL, verbose_name='На руках у ...'),
        ),
        migrations.AddField(
            model_name='bookreserved',
            name='book',
            field=models.ForeignKey(help_text='Выберите книгу для бронирования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='book.books', verbose_name='Книга'),
        ),
        migrations.AddField(
            model_name='bookreserved',
            name='reader',
            field=models.ForeignKey(help_text='Укажите читателя который бронирует книгу', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
    ]
