# Generated by Django 3.2.16 on 2023-04-13 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksrent',
            name='reader',
            field=models.ForeignKey(help_text='Укажите Читателя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
        migrations.AddField(
            model_name='books',
            name='rented_by',
            field=models.ForeignKey(blank=True, help_text='Укажите пользователя, у которого книга находиться на руках', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_books', to=settings.AUTH_USER_MODEL, verbose_name='На руках у ...'),
        ),
    ]
