# Generated by Django 3.2.16 on 2023-04-10 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(help_text='Введите Автора книги', max_length=300, verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(help_text='Напишите описание для книги', max_length=3000, verbose_name='Краткое описание книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(help_text='Напишите жанр книги', max_length=50, verbose_name='Жанр книги'),
        ),
        migrations.AlterField(
            model_name='books',
            name='rented_by',
            field=models.ForeignKey(blank=True, help_text='Укажите пользователя, у которого книга находиться на руках', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_books', to=settings.AUTH_USER_MODEL, verbose_name='На руках у ...'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(db_index=True, help_text='Введите название книги', max_length=300, unique=True, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='booksrent',
            name='book',
            field=models.ForeignKey(help_text='Укажите Книгу', on_delete=django.db.models.deletion.CASCADE, to='book.books', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='booksrent',
            name='reader',
            field=models.ForeignKey(help_text='Укажите Читателя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
        migrations.AlterField(
            model_name='booksrent',
            name='rented_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Укажите дату выдачи книги читателю', verbose_name='Дата выдачи книги'),
        ),
        migrations.AlterField(
            model_name='booksrent',
            name='returned_date',
            field=models.DateField(blank=True, help_text='Укажите дату возврата книги читателем', null=True, verbose_name='Дата возврата книги'),
        ),
    ]
