# Generated by Django 3.2.16 on 2023-04-15 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksrent',
            old_name='returned_date',
            new_name='returned_at',
        ),
        migrations.AlterField(
            model_name='booksrent',
            name='book',
            field=models.ForeignKey(help_text='Укажите Книгу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rents', to='book.books', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='booksrent',
            name='reader',
            field=models.ForeignKey(help_text='Укажите Читателя', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Читатель'),
        ),
        migrations.AlterField(
            model_name='booksrent',
            name='rented_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Укажите дату выдачи книги читателю', verbose_name='Дата выдачи книги'),
        ),
    ]
