# Generated by Django 3.2.16 on 2023-04-25 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksrent',
            options={'ordering': ('fixed_returned_at',), 'verbose_name': 'Книгу в аренде', 'verbose_name_plural': 'Книги в аренде'},
        ),
        migrations.CreateModel(
            name='BookReserved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_from', models.DateTimeField(verbose_name='Дата бронирования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус бронирования Активно/Нет')),
                ('book', models.ForeignKey(help_text='Выберите книгу для бронирования', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='book.books', verbose_name='Книга')),
                ('reader', models.ForeignKey(help_text='Укажите читателя который бронирует книгу', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Читатель')),
            ],
            options={
                'verbose_name': 'Забронированные книги',
                'ordering': ('reserved_from',),
            },
        ),
    ]
