# Generated by Django 3.2.16 on 2023-04-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_booksrent_rented_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrent',
            name='rented_at',
            field=models.DateField(blank=True, help_text='Укажите дату выдачи книги читателю', null=True, verbose_name='Дата выдачи книги'),
        ),
    ]
