# Generated by Django 3.2.16 on 2023-04-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20230425_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreserved',
            name='reserved_from',
            field=models.DateField(verbose_name='Дата бронирования'),
        ),
    ]
