# Generated by Django 3.2.16 on 2023-04-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_booksrent_rented_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrent',
            name='rented_at',
            field=models.DateTimeField(help_text='Укажите дату выдачи книги читателю', verbose_name='Дата выдачи книги'),
        ),
        migrations.AlterField(
            model_name='booksrent',
            name='returned_at',
            field=models.DateTimeField(blank=True, help_text='Укажите дату возврата книги читателем', null=True, verbose_name='Дата возврата книги'),
        ),
    ]
