# Generated by Django 3.2.16 on 2023-04-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookreserved_reserved_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreserved',
            name='reserved_from',
            field=models.DateTimeField(verbose_name='Дата бронирования'),
        ),
    ]
