# Generated by Django 3.2.16 on 2023-04-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20230415_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksrent',
            options={'ordering': ('reader',), 'verbose_name': 'Книгу в аренде', 'verbose_name_plural': 'Книги в аренде'},
        ),
    ]
