# Generated by Django 3.2.16 on 2023-04-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20230417_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrent',
            name='rented_at',
            field=models.DateTimeField(help_text='Укажите дату выдачи книги читателю', verbose_name='Дата выдачи книги'),
        ),
    ]
