# Generated by Django 3.2.16 on 2023-04-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_booksrent_rented_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrent',
            name='rented_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Укажите дату выдачи книги читателю', verbose_name='Дата выдачи книги'),
        ),
    ]
