# Generated by Django 3.2.16 on 2023-04-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20230417_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksrent',
            old_name='returned_at',
            new_name='fixed_returned_at',
        ),
        migrations.AddField(
            model_name='booksrent',
            name='fact_returned_at',
            field=models.DateTimeField(blank=True, help_text='Укажите фактическую дату возврата книги', null=True, verbose_name='Фактическая дата возврата книги'),
        ),
    ]
