# Generated by Django 3.2.16 on 2023-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20230419_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrent',
            name='fact_returned_at',
            field=models.DateTimeField(blank=True, help_text='Укажите фактическую дату возврата книги читателем', null=True, verbose_name='Фактическая дата возврата книги'),
        ),
        migrations.AlterField(
            model_name='booksrent',
            name='fixed_returned_at',
            field=models.DateTimeField(blank=True, help_text='Укажите фиксированную дату возврата книги читателем', null=True, verbose_name='Фиксированная дата возврата книги'),
        ),
    ]
