# Generated by Django 3.2.16 on 2023-04-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_deletedreaders_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedreaders',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата удаления профиля.'),
        ),
    ]
