# Generated by Django 3.2.16 on 2023-04-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_score_readers_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readers',
            name='reputation',
        ),
    ]
