# Generated by Django 3.2.16 on 2023-04-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_readers_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='readers',
            name='reputation',
            field=models.IntegerField(default=10, verbose_name='Рейтинг Читателя'),
        ),
    ]
