# Generated by Django 3.2.16 on 2023-04-21 15:34

import django.contrib.auth.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_readers_reputation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedReaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Введите username упользователя', max_length=100, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username')),
                ('first_name', models.CharField(help_text='Введите Имя', max_length=50, verbose_name='Имя читателя')),
                ('last_name', models.CharField(help_text='Введите Фамилию', max_length=50, verbose_name='Фамилия читателя')),
                ('email', models.EmailField(help_text='Введите электронную почту', max_length=254, unique=True, verbose_name='email читателя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('reputation', models.IntegerField(verbose_name='Рейтинг Читателя')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Удаленный Читатель',
                'verbose_name_plural': 'Удаленные Читатели',
                'ordering': ('username',),
            },
        ),
    ]
